apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aami

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

images:
  - name: aami/config-server
    newTag: latest

commonLabels:
  app.kubernetes.io/name: config-server
  app.kubernetes.io/part-of: aami
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: config-server-config
    behavior: merge
    literals: []

secretGenerator:
  - name: config-server-secret
    behavior: merge
    literals: []
